schema_version = "1.0.0"
id = "ddds_blenderutils"
name = "DDDs Blenderutils"
version = "2.2.0"
tagline = "Small utility extension"
maintainer = "Daniel D. Dauersuff <david@mh-network.net>"
type = "add-on"
website = "https://github.com/DavidH49/blenderutils"
tags = ["3D View", "Object"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]